name: Bump

on:
  workflow_dispatch:

  pull_request: # todo: rm
    branches: [main]

jobs:
  bump:
    # todo: rm
    if: github.event.pull_request.head.ref == 'ci/release'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Bump versions
        run: deno run -A internal/package.ts --bump
        env:
          GITHUB_ACTOR: "${{ github.actor }}"
          GITHUB_EMAIL: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
